### PR TITLE
Patch relnotes.k8s.io to release v1.26.0-alpha.2

### PR DESCRIPTION
**Pull request by ramrodo**
Automated patch to update relnotes.k8s.io to k/k version `v1.26.0-alpha.2`

### CODE REVIEW

**Review by harshanarayana — APPROVED** [review]
/lgtm

**Comment by ramrodo** [comment]
/assign @justaugustus @saschagrunert 
This PR was pending to update of the latest release notes for alpha.2

**Review by laxmikantbpandhare — APPROVED** [review]
/lgtm

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
