### PR TITLE
Patch relnotes.k8s.io to release v1.28.0-alpha.1

### PR DESCRIPTION
**Pull request by sanchita-07**
Automated patch to update relnotes.k8s.io to k/k version `v1.28.0-alpha.1`

### CODE REVIEW

**Comment by rashansmith** [comment]
@sanchita-07  In the preview view https://deploy-preview-532--kubernetes-sigs-release-notes.netlify.app/?releaseVersions=1.28.0-alpha.1, a few of the notes including #113969 and #114514 have the format where content is in bold, starts with backticks, and end with a colon. Is this format expected?

release_screenshot

**Comment by sanchita-07** [comment]
Nope, thanks for the pointers. :smiley:

**Comment by rashansmith** [comment]
@sanchita-07 Release Note #114746 has "NONE" instead of NONE. Also #117690 seems to just be an error message for the release note content. Is that ok?

**Comment by sanchita-07** [comment]
Normally, these automated patches are created using krel for updating the release notes website. One can refer to the PRs from previous releases as a reference.

**Comment by cici37** [comment]
You should fix release notes under sig-release before updating here. https://github.com/kubernetes/sig-release/blob/master/releases/release-1.28/release-notes/maps/pr-113969-map.yaml should not exist if no release note.

**Comment by sanchita-07** [comment]
PTAL @saschagrunert

**Review by cpanato — APPROVED** [review]
/lgtm

**Comment by sanchita-07** [comment]
Thanks @cpanato

**Pull request merged**
