### PR TITLE
Patch relnotes.k8s.io to release v1.21.0

### PR DESCRIPTION
**Pull request by ashnehete**
Automated patch to update relnotes.k8s.io to k/k version `v1.21.0`

### CODE REVIEW

**Comment by wilsonehusin** [comment]
w00t!

/lgtm

**Review by soniasingla — APPROVED** [review]
/lgtm

Thanks @ashnehete 🎉

**Comment by wilsonehusin** [comment]
🤨 tests were run but the label seem inconsistent?

/ok-to-test

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
