### PR TITLE
Remove unused ViewChild members

### PR DESCRIPTION
**Pull request by saschagrunert**
ViewChilds are not used any more so we're safe to remove them.

### CODE REVIEW

**Comment by justaugustus** [comment]
LGTM, but will leave Jeff to approve.
/assign @jeefy

**Comment by saschagrunert** [comment]
@jeefy do I have to do anything here or do you think we can merge this? :)

**Comment by jeefy** [comment]
Totally mergeable, I got distracted and this sat.

/lgtm

**Comment by saschagrunert** [comment]
Thanks :pray: 

/retest

**Pull request merged**
