### PR TITLE
Patch relnotes.k8s.io to release v1.20.2

### PR DESCRIPTION
**Pull request by ashnehete**
Automated patch to update relnotes.k8s.io to k/k version `v1.20.2`

### CODE REVIEW

**Comment by sladyn98** [comment]
The notes in this are already good to go right so since it is an automated patch
 LGTM :+1:

**Comment by wilsonehusin** [comment]
yeah I think so

/lgtm

**Review by soniasingla — APPROVED** [review]
/lgtm

Thanks for the patch 🎖

**Comment by puerco** [comment]
Thanks everyone !
/ok-to-test
/approve

**Pull request merged**
