### PR TITLE
Patch relnotes.k8s.io to release v1.19.1

### PR DESCRIPTION
**Pull request by puerco**
Automated patch to update relnotes.k8s.io to k/k version `v1.19.1`

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by saschagrunert** [comment]
@puerco can you propose to add yourself to the app rovers? Looks like we need more and your contributions to this project are very welcome. ☺️

**Comment by puerco** [comment]
Thanks @saschagrunert there it is: https://github.com/kubernetes-sigs/release-notes/pull/197

**Pull request merged**
