### PR TITLE
Patch relnotes.k8s.io to release v1.23.0

### PR DESCRIPTION
**Pull request by cici37**
Automated patch to update relnotes.k8s.io to k/k version `v1.23.0`

### CODE REVIEW

**Comment by reylejano** [comment]
Since PR https://github.com/kubernetes-sigs/release-notes/pull/254 merged, this PR might need to rebase but the bot hasn't applied the `needs-rebase` label at this time

**Comment by reylejano** [comment]
:) , I commented too soon
Please rebase :)

**Comment by puerco** [comment]
Thanks Cici and Rey!!!!
/approve

**Pull request merged**
