### PR TITLE
WIP: Propose KEP layout

### PR DESCRIPTION
**Pull request by saschagrunert**
This is a very rough first idea how to show KEPs instead of release notes on the same website layout. A lot of tests are still broken and we would need to continue the renaming/implementing filtering if we can agree on a layout.

What works:
- filtering by text
- filtering by participating and owning SIG
- collapsing/showing the KEPs content

Preview: https://deploy-preview-140--kubernetes-sigs-release-notes.netlify.com/
Relates to https://github.com/kubernetes/enhancements/pull/1467

### CODE REVIEW

**Comment by dims** [comment]
cc @palnabarun

**Comment by saschagrunert** [comment]
Updated to match the new JSON layout proposed in https://github.com/kubernetes/enhancements/pull/1505

**Comment by justaugustus** [comment]
@saschagrunert -- Looks great so far!
Let's plan to reopen this in k/enhancements once https://github.com/kubernetes/enhancements/pull/1545 merges.

/close

**Pull request closed without merging**
