### PR TITLE
Add travis code coverage collecting and badge

### LINKED ISSUE #5: Update unit testing to use jest
I'd like to suggest to switch to [jest](https://jestjs.io/) for unit testing purposes. It has a lots of great features and could be integrated well into the CI. I see the following steps needed to achieve this goal:

- [x] Add jest and drop karma dependency
- [x] Add jest configuration and verify unit tests (#27)
- [x] Add coverage report to CI including badge (#35)

### PR DESCRIPTION
**Pull request by saschagrunert**
Closes #5

### CODE REVIEW

**Comment by saschagrunert** [comment]
@jeefy Would you like to support me in the travis-setup? :innocent: Usually only the project needs to be enabled right now.

**Comment by jeefy** [comment]
It feels a little dirty enabling Travis just to upload code coverage metrics, and I don't like the idea that we'd have CI jobs split between two different providers. I think this should be possible to do in a Prow job, and the Jenkins example for `codecov` seems basic enough to modify for our purposes.

Thoughts?

**Comment by saschagrunert** [comment]
> It feels a little dirty enabling Travis just to upload code coverage metrics, and I don't like the idea that we'd have CI jobs split between two different providers. I think this should be possible to do in a Prow job, and the Jenkins example for `codecov` seems basic enough to modify for our purposes.
> 
> Thoughts?

Yes I agree, I will modify the current unit-test proj job for this.

**Comment by justaugustus** [comment]
+1 on keeping all tests/checks in prow.

**Comment by saschagrunert** [comment]
Rebased on top of the latest master branch

**Comment by jeefy** [comment]
I think I said this in other channels, but I don't like the idea of integrating with Travis just to use/get codecov info. We could probably integrate it with Prow eventually.

That said, we should probably close this rather than leave it dangling.

@saschagrunert Thoughts?

**Comment by saschagrunert** [comment]
Sure, let’s close it for now

**Pull request closed without merging**
