### PR TITLE
Adding release notes for 1.17.0 alpha 2 and 3.

### PR DESCRIPTION
**Pull request by bridgetkromhout**
Following the method in https://github.com/kubernetes/sig-release/blob/master/release-team/role-handbooks/release-notes/patch-notes.md I'm adding release notes for 1.17.0 alpha 2 and 3. (Alpha 1 is already in progress in https://github.com/kubernetes-sigs/release-notes/pull/112.)

### CODE REVIEW

**Comment by cartyc** [comment]
Thanks @bridgetkromhout !

/lgtm

**Comment by jeefy** [comment]
/hold

Oops! Couple things. :( 

1) More of an FYI, the PR for the 1.17.0-alpha.1 got closed because it had some erroneous files in there. :(
2) The two JSON files (`release-notes-1.17.0-alpha.2.json` and `release-notes-1.17.0-alpha.3.json`) need to be under the `src/asssets/` folder to be picked up, otherwise things break.
3) Because I've been on PTO/Travel the last two weeks I'm playing PR catch-up and those merges caused a conflict. Yay Git (Sorry) so you'll need to resolve the conflict on top of tackling number 2.

The fact that 2) even happened is a problem, and we should somehow catch any files that are added but don't exist. I'll create an issue for that.

**Comment by bridgetkromhout** [comment]
Thanks, @jeefy!

> More of an FYI, the PR for the 1.17.0-alpha.1 got closed because it had some erroneous files in there. :(

As I understand it, this is being fixed, so I didn't add anything for that one.

> The two JSON files (release-notes-1.17.0-alpha.2.json and release-notes-1.17.0-alpha.3.json) need to be under the src/asssets/ folder to be picked up, otherwise things break.

Oops, sorry 'bout that. I didn't noticed I dropped them in the wrong place when I regenerated them this morning right before submitting the PR.

> Because I've been on PTO/Travel the last two weeks I'm playing PR catch-up and those merges caused a conflict. Yay Git (Sorry) so you'll need to resolve the conflict on top of tackling number 2.

Sorry for the hassle. I pulled in master, rearranged my contributions so they're listed in the right place/order in that file, and put them in the right place in the filesystem.

Please let me know about anything else I'll need to complete! Thanks.

**Comment by jeefy** [comment]
No hassle at all. :) Thanks for the quick turn around.

/approve
/lgtm
/honk

**Comment by bridgetkromhout** [comment]
> Thanks for the quick turn around.

I'm on a plane (as per usual) so plenty of time for github. Is there something further we should finish to get the `do not merge/hold` label removed?

**Comment by jeefy** [comment]
I need to honk less and read more. 

/hold cancel

**Pull request merged**
