### PR TITLE
Add 'additional documentation' section

### PR DESCRIPTION
**Pull request by saschagrunert**
Update all data models to consume the new optional `documentation` field
within the data JSON. The notes component has been adapted as well to
display these information.

---

How to test this:

```
> cp src/testdata/release-notes.json src/assets/data/release-notes-1.16.json
> npm install
> npm start
```

Now the 1.16 alpha release note should show up the `related documentation` section, like this:
screenshot

I'm hoping for additional feedback about how to improve the layout. :pray: It is currently not searchable as well, which seems to be something we should do definitely. End-to-end tests are missing, too.

Relates to https://github.com/kubernetes/sig-release/issues/667

### CODE REVIEW

**Comment by jeefy** [comment]
My initial thoughts when thinking about layout: Have a book icon in the header, and/or a link that says "Additional Documentation". When clicked, a modal pops up with links to said docs.

I'm a fan of "less clicks is better" but I also feel like putting the docs at the bottom of every entry may get SUPER cluttered.

The addition of these docs may also warrant tearing down the design of note component and starting clean.

**Comment by saschagrunert** [comment]
Alright @jeefy, how is that one: You now have the blue icon on top and if you click on it, it shows up the "Additional documentation" part of the cards content.

Like this, before the click on the icon:
before

And after click on the icon:
screenshot

Do you like it, or would you prefer a modal?

I think we still can improve the layout of the docs `<ul>`, like having different colors for the labels and making the layout more nice :thinking: WDYT?

**Comment by jeefy** [comment]
Yasssss. That's what I was thinking. Now my only concern from a user perspective is: Would I know that I can click on that book, and get documentation?

Unless you have ideas and want to block on this, I'd say we merge this in and iterate.

**Comment by saschagrunert** [comment]
> Yasssss. That's what I was thinking. Now my only concern from a user perspective is: Would I know that I can click on that book, and get documentation?

Okay, how about a tooltip:
screenshot

> Unless you have ideas and want to block on this, I'd say we merge this in and iterate.

I gave it a slight overhaul and made the badges to show-up in different colors, like this:
res

So if you don't have anything else I would say I'm done here :innocent:

**Comment by saschagrunert** [comment]
As a follow-up I see two major points:
- End to end tests for the UI
- Filtering for the documentation

**Pull request merged**
