### PR TITLE
Update to angular 14.2

### LINKED ISSUE #255: Update angular
We require more maintainers of this project, while updating angular seems to be a good first issue to get used to the code base.

/help
/good-first-issue

### PR DESCRIPTION
**Pull request by harshanarayana**
Upgrade all angular components and dependencies from 11.1 to  to 14.2

Fixes #255

### CODE REVIEW

**Comment by saschagrunert** [comment]
@harshanarayana I removed the draft state for now if that's fine.

**Comment by harshanarayana** [comment]
> @harshanarayana I removed the draft state for now if that's fine.

@saschagrunert  No worries :) Thanks for doing that

**Comment by harshanarayana** [comment]
Yay!!! All the tests are green. Thanks for the help @saschagrunert  @ramrodo  and @cpanato  🙇‍♂️

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
