### PR TITLE
Update data flow to use redux

### PR DESCRIPTION
**Pull request by saschagrunert**
This introduces the redux architecture for the filter component and adapts all other components to not use direct value binding any more. Added a separate end to end test for URL path handling.

### CODE REVIEW

**Comment by saschagrunert** [comment]
/hold

I'm seeing a bug.

**Comment by saschagrunert** [comment]
/hold cancel

I see the bug in the master as well and will come up with a separate fix.

**Comment by saschagrunert** [comment]
That is a bigger refactoring than initially thought, sorry for that :pray:

**Comment by jeefy** [comment]
/approve
/lgtm

🌮 @saschagrunert You seriously rock.

**Pull request merged**
