### PR TITLE
Patch relnotes.k8s.io with release v1.18.0-beta.1

### PR DESCRIPTION
**Pull request by reylejano-rxm**
release-notes \
  --branch=master \
  --repo-path  /var/folders/35/m9zql4dj7t3_bq6qsq567vqc0000gn/T/k8s \
  --release-version 1.18.0-beta.1 \
  --format json \
  --output src/assets/release-notes-1.18.0-beta.1.json  \
  --start-rev v1.18.0-beta.0 \
  --end-rev v1.18.0-beta.1
npm run prettier

cc/ @saschagrunert @evillgenius75 @puerco @JamesLaverack

### CODE REVIEW

**Comment by reylejano-rxm** [comment]
@saschagrunert I forgot to amend src/environment/assets.ts with the latest version
Can I cancel this PR request and resubmit?

**Comment by puerco** [comment]
@reylejano-rxm  you missed adding the json file to the assets

**Comment by saschagrunert** [comment]
Ah yes, I did not notice that. :)

**Comment by reylejano-rxm** [comment]
canceling and submitting a new PR with amended assets.ts

**Pull request closed without merging**
