### PR TITLE
Fix badge selection and add e2e tests

### PR DESCRIPTION
**Pull request by saschagrunert**
Closes https://github.com/kubernetes-sigs/release-notes/issues/128

### CODE REVIEW

**Comment by saschagrunert** [comment]
@jeefy may I ask you to drop a lgtm here? :)

**Comment by saschagrunert** [comment]
@jeefy pinging again, can we LGTM this?

**Comment by saschagrunert** [comment]
@jeefy let's merge those as well :)

**Comment by jeefy** [comment]
Wow. I suck. Ping me on Slack if I'm being this slow. :cry: 

/lgtm

**Comment by saschagrunert** [comment]
Ah, I had to rebase to fix the prettier issues…

**Pull request merged**
