### PR TITLE
Patch relnotes.k8s.io to release v1.18.12

### PR DESCRIPTION
**Pull request by puerco**
Automated patch to update relnotes.k8s.io to k/k version `v1.18.12`

### CODE REVIEW

**Comment by saschagrunert** [comment]
Unfortunately this now needs a rebase.

**Comment by ashnehete** [comment]
Created new PR for this version
https://github.com/kubernetes-sigs/release-notes/pull/227

**Comment by saschagrunert** [comment]
This one has been superseded
/close

**Pull request closed without merging**
