### PR TITLE
Patch relnotes.k8s.io to release v1.18.12

### PR DESCRIPTION
**Pull request by puerco**
Automated patch to update relnotes.k8s.io to k/k version `v1.18.12`

### CODE REVIEW

**Comment by puerco** [comment]
Mmmmh... due to the github issue when cutting this release, I think we will have to generate v1.18.12 with all changes starting from v1.18.10 instead of .11
/hold

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Review by saschagrunert — CHANGES_REQUESTED** [review]
Ooops, `src/assets/release-notes-1.18.12.json` is an empty file.

**Comment by puerco** [comment]
Resending ..
/close

**Pull request closed without merging**
